### ISSUE TITLE
Facilitate onboarding flow

### ISSUE THREAD

**Issue by alexzhaohong** [zetaroid/pokeDiscordPublic#1]
Issue: `/help` route does not provide guidance

Steps to create issue:
1. Authorize PokeNav
2. Click on PokeNav avatar
3. Read `on 840 servers with 3166 trainers! | /help`
4. type `/help` command
5. Bot responds `{user}, Professor Birch will assist you in your Direct Messages.`
6. No DM is sent by bot

How I solved:
* Read #faq-and-rules in 'PokeNav Official Server' on Discord, saw `!start` command
* Used `!start` in DM to PokeNav bot, then `!start` in channel
* receive message that slash commands will be mandatory starting April 2022
* use `/start` in channel

**Comment by zetaroid** [comment]
Resolved. Thank you.
